# Generated by Django 6.1 on 2026-09-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panchayat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='notice_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
