# Generated by Django 6.1 on 2026-09-13 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panchayat', '0002_alter_notice_notice_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanchayatFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=20)),
                ('fund_type', models.CharField(choices=[('GENERAL', 'General Fund'), ('FINANCE', 'Finance Commission'), ('SCHEME', 'Government Scheme'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.CharField(max_length=300)),
                ('amount_received', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_spent', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='notice',
            name='notice_date',
            field=models.DateField(),
        ),
    ]
